name: Build

on:
  push:
    branches: [ main ]
    paths:
      - 'kernel/**'
      - 'Makefile'
      - '.github/workflows/**'
      - 'include/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'kernel/**'
      - 'Makefile'
      - '.github/workflows/**'
      - 'include/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.c', '**/*.h', '**/*.asm') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Install dependencies
        run: sudo apt install -y clang nasm xorriso ccache

      - name: Build project (Release Mode)
        run: time make -j$(nproc) MODE=Release

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: wind-iso
          path: build/out/wind.iso
