name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'sys/**'
      - 'Makefile'
      - '.github/workflows/**'
      - 'include/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'sys/**'
      - 'Makefile'
      - '.github/workflows/**'
      - 'include/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, gcc]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.c', '**/*.h', '**/*.asm') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Install dependencies
        run: sudo apt install -y clang gcc nasm xorriso ccache

      - name: Build project (Release Mode)
        run: time make -j$(nproc) MODE=Release CC=${{ matrix.compiler }}

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: wind-iso-${{ matrix.compiler }}
          path: build/out/wt.iso
