name: Build Wind ISO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang nasm xorriso ccache

      - name: Build project (Release)
        run: make MODE=Release

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: wind-iso
          path: build/out/wind.iso
